---
signal:
    sr: 16000
    frame_shift: 0.005
    frame_length:  0.025
    win_length: 400
    hop_length: 80
    n_fft: 512
    n_mels: 80
    max_db: 35
    min_db: -55
    max_length: 32000
model:
    dilations: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
#                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
    filter_width: 2
    residual_channels: 32
    dilation_channels: 32
    skip_channels: 256
    condition_channels: 32
    use_biases: True
    n_iaf: 4
    normalize: 'in'
    condition_all_iaf: True
    cond_upsample_method: 'repeat'
    use_skip_connection: True
    no_norm_cond: False
train:
    data_path: '/data/private/vc/datasets/arctic/slt/*.wav'
    batch_size: 8
    lr: 0.0002
    n_mix: 10
    weight_power_loss: 0.
    num_epochs: 100000
    steps_per_epoch: 100
    save_per_epoch: 100
    num_gpu: 8
    loss: 'l1'
generate:
    length: 64000
    data_path: '/data/private/vc/datasets/arctic/slt/*.wav'
#    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
    batch_size: 3
    every_n_epoch: 10
logdir_path: '/data/private/iaf-vocoder/logdir'
debug_port: 1028