---
signal:
    sr: 16000
    win_length: 400
    hop_length: 80
    n_fft: 512
    n_mels: 80
    max_db: 35
    min_db: -55
    max_length: 32000
model:
    dilations: [
                 [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
                 [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
                 [1, 2, 4, 8, 16, 32, 64, 128, 256, 512],
                 [
                   1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                   1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                   1, 2, 4, 8, 16, 32, 64, 128, 256, 512
                 ]
               ]
    filter_width: 2
    residual_channels: 64
    dilation_channels: 64
    skip_channels: 128
    condition_channels: 80
    use_biases: True
    n_iaf: 4
    normalize: ''
    normalize_cond: ''
    normalize_wavenet: ''
    condition_all_iaf: True
    cond_upsample_method: 'repeat'
    use_skip_connection: False
train:
    data_path: '/data/private/vc/datasets/arctic/slt/*.wav'
    batch_size: 2
    num_gpu: 8
    lr: 0.0002
    n_mix: 10
    weight_power_loss: 0.
    num_epochs: 100000
    steps_per_epoch: 100
    save_per_epoch: 100
    loss: 'l1'
    adam_beta2: 0.999
generate:
    length: 64000
    data_path: '/data/private/vc/datasets/arctic/slt/*.wav'
#    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
    batch_size: 3
    every_n_epoch: 10
logdir_path: '/data/private/iaf-vocoder/logdir'
debug_port: 1028