---
signal:
    sr: 16000
    frame_shift: 0.005
    frame_length:  0.025
    win_length: 400
    hop_length: 80
    n_fft: 512
    n_mels: 80
    max_db: 35
    min_db: -55
    max_length: 32000
model:
    dilations: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512,
                  1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
    filter_width: 2
    residual_channels: 32
    dilation_channels: 32
    quantization_channels: 256
    skip_channels: 512
    use_biases: True
    initial_filter_width: 32
    n_iaf: 4
logdir_path: '/data/private/vc/logdir'
train:
    data_path: '/data/private/vc/datasets/timit/TIMIT/TRAIN/*/*/*.wav'
    batch_size: 32
    n_mix: 5
    lr: 0.0003
    num_epochs: 1000
    steps_per_epoch: 100
    save_per_epoch: 2
    num_gpu: 2
test:
    data_path: '/data/private/vc/datasets/arctic/slt/*.wav'
    batch_size: 32