test/default:
  train:
    batch_size: 1
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    steps_per_epoch: 1
    num_gpu: 1
  generate:
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    every_n_epoch: 1
test/tran:
  model:
    cond_upsample_method: 'transposed_conv'
  train:
    batch_size: 1
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    steps_per_epoch: 1
    num_gpu: 1
  generate:
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    every_n_epoch: 1
test/ema:
  train:
    batch_size: 1
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    steps_per_epoch: 1
    num_gpu: 1
    use_ema: True
  generate:
    data_path: '/data/private/vc/datasets/arctic/slt/arctic_a0001.wav'
    every_n_epoch: 1

---
logistic/no_norm_all:
  model:
    normalize: ''
    normalize_cond: ''
    normalize_wavenet: ''
  train:
    batch_size: 1
    num_gpu: 8
logistic/no_norm_tran:
  model:
    cond_upsample_method: 'transposed_conv'
    normalize: ''
    normalize_cond: ''
    normalize_wavenet: ''
  train:
    batch_size: 1
    num_gpu: 8
logistic/no_norm_lj:
  model:
    normalize: ''
    normalize_cond: ''
    normalize_wavenet: ''
  train:
    batch_size: 1
    num_gpu: 8
    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
  generate:
    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
logistic/power:
  train:
    batch_size: 1
    num_gpu: 4
    weight_power_loss: 0.0005